language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.1
  - 3.2
before_install: sudo apt-get install subversion bzr mercurial git-core
install: pip install nose virtualenv scripttest mock
script: nosetests
notifications:
branches:
  only:
    - develop
env:
  - PIP_USE_MIRRORS=true

